### ISSUE TITLE
Plugin errors on new 2020.2 build

### ISSUE THREAD

**Issue by slavoroi** [lppedd/idea-conventional-commit-commitlint#4]
Ubuntu 20.04
Build #WS-202.6397.88, built on July 24, 2020

Error of:
2:33 PM	Plugin Error: Plugin "Commitlint Conventional Commit" is incompatible (until build 201.SNAPSHOT < WS-202.6397.88).

I can see that I have autocomplete but i have failures on webstorm start. 

Please help us with this issue.

**Comment by lppedd** [comment]
@slavoroi @AprilViolet Updated to support up to IDEA 2020.3
You can find the `zip` file under https://github.com/lppedd/idea-conventional-commit-commitlint/releases.
Or you can wait for it to be approved on the [JetBrains Plugin marketplace](https://plugins.jetbrains.com/plugin/14046-commitlint-conventional-commit).
